import threading

from pysim_sdk.nic.nic import BaseNetworkInterface


class SpiInterface(BaseNetworkInterface):
    if_type = "spi"

    def __init__(
        self, name, events_sink, spi_in, spi_out, ip_addr=None, next_hop_ip_addr=None
    ):
        """
        name: Identifier of the interface (e.g. `spi1`)
        events_sink: Sink queue where events generated by this interface will be sent.
        next_hop: SpiInterface object where outgoing packets will be pushed to. You will
                  manually need to set this property for the first interface in the loop
                  by setting `self.next_hop` attribute to the corresponding value.

        Events that may be pushed to the queue are:
         - PacketReceived - Generated when a packet reaches this interface.
        """
        self.name = name
        self.events_sink = events_sink
        self.spi_in = spi_in
        self.spi_out = spi_out
        self.ip_addr = ip_addr
        self.next_hop_ip_addr = next_hop_ip_addr
        self.mask = "255.255.255.0"
        self._thread = threading.Thread(target=self._spi_main, name="spi")

    def send_packet(self, packet: bytes):
        """
        Sends a packet to the next hop. Note that the `next_hop` property must have
        been properly set before calling this method.
        """
        self.count_packet_out(packet)
        self.spi_out.put(packet)

    def recv_packet(self, ip_packet: bytes):
        """
        Receives a packet from an external interface.
        """
        self.count_packet_in(ip_packet)
        self.events_sink.put((self, "packet-received", ip_packet))

    def __enter__(self):
        self._thread.start()
        return self

    def _spi_main(self):
        while packet := self.spi_in.get():
            self.recv_packet(packet)

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.spi_in.put(None)
        self._thread.join()

    def __str__(self):
        return self.name
